update

diff --git a/getdepth b/getdepth
--- a/getdepth
+++ b/getdepth
@@ -1,13 +1,44 @@
 #!/bin/bash
+r_chr=""
+r_start=0;
+r_end=0;
+while getopts ":hr:s:e:" opt; do
+        case ${opt} in
+                h )
+                        echo "getdepth_dir -r chrname -s start -e end (1-based) samfile(bamfile) outfile"
+			echo "default:"
+                        echo -e "\t-r [empty]"
+			echo -e "\t-s 0"
+			echo -e "\t-e INF"
+                        exit 0;;
+                r )
+                        r_chr=$OPTARG;;
+                s )
+                        r_start=$OPTARG;;
+                e )
+                        r_end=$OPTARG;;
+                \? )
+                        echo "Invalid option: $OPTARG" 1>&2;;
+                : )
+                        echo "Invalid option: $OPTARG requires an argument" 1>&2;;
+        esac
+done
+shift $((OPTIND - 1))
+
+
 if [ "$#" -ne 2 ]; then
-        echo "getdepth_dir samfile(bamfile) outfile"
+	echo "getdepth_dir -r chrname -s start -e end (1-based) samfile(bamfile) outfile"
+	echo "default:"
+	echo -e "\t-r [empty]"
+        echo -e "\t-s 0"
+        echo -e "\t-e INF"
         exit 0
 fi
 
 samfile=$1
 outfile=$2
 
-samtools view $samfile | awk '
+samtools view $samfile | awk -v r_chr=$r_chr -v r_start=$r_start -v r_end=$r_end '
 function parse_cigar(cigar_str, cigar_num, cigar_type){
 	delete cigar_num;
         delete cigar_type;
@@ -24,6 +55,7 @@ function parse_cigar(cigar_str, cigar_num, cigar_type){
 }       
 	
 {
+	chr=$3
 	tStart = $4
 	tEnd = tStart
 	parse_cigar($6, cigar_num, cigar_type);
@@ -39,15 +71,25 @@ function parse_cigar(cigar_str, cigar_num, cigar_type){
 		}
         }      
 	tEnd = tEnd - 1
-
-	for (i=tStart; i<=tEnd; i++){
-		cvg[i]+=1
+	
+	if (chr == r_chr || r_chr == ""){
+		for (i=tStart; i<=tEnd; i++){
+			if (i >= r_start){
+				if (i <= r_end || r_end == 0){
+					cvg[chr][i]+=1
+				}
+			}
+		}
 	}
 }
 END{
-	for (i=1; i<=length(cvg); i++){
-		printf("%d\t%d\n", i, cvg[i])
-	} 
+	for (ref in cvg){
+		for (i = 1; i <= length(cvg[ref]); i++){
+			if (cvg[ref][i] >0 ){
+				printf("%s\t%d\t%d\n", ref, i, cvg[ref][i])
+			}
+		}
+	}
 }
 ' > $outfile
 
diff --git a/getdepth_dir b/getdepth_dir
--- a/getdepth_dir
+++ b/getdepth_dir
@@ -1,7 +1,54 @@
 #!/bin/bash
+
+walltime=2
+memory=4
+queue="premium"
+r_chr=""
+r_start=0;
+r_end=0;
+while getopts ":hw:m:q:r:s:e:" opt; do
+        case ${opt} in
+                h )
+                        echo "USAGE: getdepth_dir -q queue -w walltime -m memory -r chrname -s start -e end (1-based) indir logdir"
+                        echo "default:"
+                        echo -e "\t-w 2"
+                        echo -e "\t-m 4"
+                        echo -e "\t-q premium"
+			echo -e "\t-r [empty]"
+                        echo -e "\t-s 0"
+                        echo -e "\t-e INF"
+                        exit 0;;
+                w )
+                        walltime=$OPTARG;;
+                m )
+                        memory=$OPTARG;;
+                q )
+                        queue=$OPTARG;;
+		r )
+                        r_chr=$OPTARG;;
+                s )
+                        r_start=$OPTARG;;
+                e )
+                        r_end=$OPTARG;;
+                \? )
+                        echo "Invalid option: $OPTARG" 1>&2;;
+                : )
+                        echo "Invalid option: $OPTARG requires an argument" 1>&2;;
+        esac
+done
+shift $((OPTIND - 1))
+
+
 if [ "$#" -ne 2 ]; then
-        echo "getdepth_dir indir logdir"
-        exit 0
+	echo "USAGE: getdepth_dir -q queue -w walltime -m memory -r chrname -s start -e end (1-based) indir logdir"
+        echo "default:"
+        echo -e "\t-w 2"
+        echo -e "\t-m 4"
+        echo -e "\t-q premium"
+        echo -e "\t-r [empty]"
+        echo -e "\t-s 0"
+        echo -e "\t-e INF"
+	exit 0
 fi
 
 indir=$1
@@ -11,8 +58,7 @@ for bamfile in $(ls $indir/*.bam);do
 	sample_name=$(basename $bamfile)
 	sample_name=${sample_name%.bam}
 	cvgfile=$indir/$sample_name.cvg
-	#cmd="submitjob -m 16 -w 8 -j $sample_name -o $logdir bamtools coverage -in $bamfile -out $cvgfile"
-	cmd="submitjob -m 16 -w 16 -j $sample_name -o $logdir getdepth $bamfile $cvgfile"
+	cmd="submitjob -q $queue -m $memory -w $walltime -j $sample_name -o $logdir getdepth -r $r_chr -s $r_start -e $r_end $bamfile $cvgfile"
 	$cmd
 done
 
