update

diff --git a/igda_pipe_phase_ont b/igda_pipe_phase_ont
--- a/igda_pipe_phase_ont
+++ b/igda_pipe_phase_ont
@@ -1,48 +1,93 @@
 #!/bin/bash
+min_cvg=10
+min_nn=25
+max_nn=50
+while getopts ":hc:t:m:" opt; do
+        case ${opt} in
+                h )
+                        echo "igda_pipe_phase_ont -c min_cvg -t min_nn -m max_nn indir reffile outdir"
+                        echo "default:"
+                        echo -e "\t-c 10, minimal coverage of each contig"
+                        echo -e "\t-t 25, minimal number of nearest neighbors"
+                        echo -e "\t-m 50, maximal number of nearest neighbors"
+                        exit 0;;
+                c )
+                        min_cvg=$OPTARG;;
+                t )
+                        min_nn=$OPTARG;;
+                m )
+                        max_nn=$OPTARG;;
+                \? )
+                        echo "Invalid option: $OPTARG" 1>&2;;
+                : )
+                        echo "Invalid option: $OPTARG requires an argument" 1>&2;;
+        esac
+done
+shift $((OPTIND - 1))
+
 if [ $# -ne 3 ] ; then
-        echo "igda_pipe_phase_ont indir(output of igda_pipe_detect_ont) reffile"
+	echo "igda_pipe_phase_ont -c mincvg -t min_nn -m max_nn indir reffile outdir"
+        echo "default:"
+        echo -e "\t-c minimal coverage of each contig"
+        echo -e "\t-t minimal number of nearest neighbors"
+        echo -e "\t-m maximal number of nearest neighbors"
 	exit 0
 fi
 
 
 indir=$1
 reffile=$2
+outdir=$3
 
+mkdir -p $outdir
 echo "indir = "$indir
 echo "reffile = "$reffile
+echo "outdir = "$outdir
+echo "min_cvg = "$min_cvg
+echo "min_nn = "$min_nn
+echo "max_nn = "$max_nn
 
 echo "Start."
 
 echo "============= dimension reduction ==========="
-igda rdim $indir/realign.encode $indir/realign.var $indir/realign.encode.rdim
+igda rdim $indir/realign.encode $indir/realign.var $outdir/realign.encode.rdim
 
 echo "============= recode ==========="
-igda recode $indir/realign.m5 $indir/realign.var $indir/realign.recode
+igda recode $indir/realign.m5 $indir/realign.var $outdir/realign.recode
 
 echo "============= ann ==========="
-ann_t=$dforest_r
-ann_m=$(($ann_t+$ann_t))
-ann_c=10
+#dforest_r=25
+#ann_t=$dforest_r
+#ann_m=$(($ann_t+$ann_t))
+#ann_c=10
+ann_c=$min_cvg
+ann_t=$min_nn
+ann_m=$max_nn
 echo "ann_t=$ann_t, ann_m=$ann_m, ann_c=$ann_c"
-igda ann -j 0.5 -c $ann_c -t $ann_t -m $ann_m  $indir/realign.recode $indir/realign.encode.rdim $indir/realign.m5 $indir/realign.var $reffile $indir/realign.ann
+igda ann -j 0.5 -c $ann_c -t $ann_t -m $ann_m  $outdir/realign.recode $outdir/realign.encode.rdim $indir/realign.m5 $indir/realign.var $reffile $outdir/realign.ann
 
 echo "============= test contigs ==========="
-igda test_contigs $indir/realign.ann $indir/realign.recode $indir/realign.m5 $reffile
+igda test_contigs -a 0.6466251 -t 21.90139 $outdir/realign.ann $outdir/realign.recode $indir/realign.m5 $reffile
 
 echo "============= calculate abundance ==========="
-igda abundance $indir/realign.ann.tested.ft $indir/realign.recode $indir/realign.m5
+igda abundance $outdir/realign.ann.tested.ft $outdir/realign.recode $indir/realign.m5
 
 echo "============= test contigs pairwisely ==========="
-igda test_contigs_pairwise $indir/realign.ann.tested.ft.count $indir/realign.recode $reffile
+igda test_contigs_pairwise -a 0.6466251 -t 21.90139 $outdir/realign.ann.tested.ft.count $outdir/realign.recode $reffile
+
+echo "============= correct contigs ==========="
+mv $outdir/realign.ann.tested.ft.count.ft $outdir/realign.ann.tested.ft.count.ft.raw
+igda correct_contigs $outdir/realign.ann.tested.ft.count.ft.raw $outdir/realign.ann.tested.ft.count.ft.ct
+sort -k2,2n -k3,3n -k1,1 -u $outdir/realign.ann.tested.ft.count.ft.ct > $outdir/realign.ann.tested.ft.count.ft
 
 echo "============= transitive reduction ==========="
-igda tred $indir/realign.ann.tested.ft.count.ft
+igda tred $outdir/realign.ann.tested.ft.count.ft
 
 echo "============= assemble ==========="
-igda assemble $indir/realign.ann.tested.ft.count.ft $indir/realign.ann.tested.ft.count.ft.tred.dot
+igda assemble $outdir/realign.ann.tested.ft.count.ft $outdir/realign.ann.tested.ft.count.ft.tred.dot
 
 echo "============= recalculate abundance ==========="
-igda abundance $indir/realign.ann.tested.ft.count.ft.assembled $indir/realign.recode $indir/realign.m5
+igda abundance $outdir/realign.ann.tested.ft.count.ft.assembled $outdir/realign.recode $indir/realign.m5
 
 echo "Done."
 
